export const categories = [
  {Id: 1, CatName: 'Arctic'},
  {Id: 2, CatName: 'Smoke and vape'},
  {Id: 3, CatName: 'Nature'},
  {Id: 4, CatName: 'Travel & Adventure'},
  {Id: 5, CatName: 'Minimalist'},
  {Id: 6, CatName: 'Bikes'},
  {Id: 7, CatName: 'Abstract'},
  {Id: 8, CatName: 'Cityscape'},
  {Id: 9, CatName: 'Animals'},
  {Id: 10, CatName: 'Sci-Fi'},
];

export const catImages = [
  {Id: 1, catID: 3, image: require('../android/app/src/main/res/drawable/image1.png')},
  {Id: 2, catID: 10, image: require('../android/app/src/main/res/drawable/image2.png')},
  {Id: 3, catID: 10, image: require('../android/app/src/main/res/drawable/image3.png')},
  {Id: 4, catID: 4, image: require('../android/app/src/main/res/drawable/image4.png')},
  {Id: 5, catID: 8, image: require('../android/app/src/main/res/drawable/image5.png')},
  {Id: 6, catID: 7, image: require('../android/app/src/main/res/drawable/image6.jpg')},
  {Id: 7, catID: 7, image: require('../android/app/src/main/res/drawable/image7.jpg')},
  {Id: 8, catID: 8, image: require('../android/app/src/main/res/drawable/image8.jpg')},
  {Id: 9, catID: 6, image: require('../android/app/src/main/res/drawable/image9.jpg')},
  {Id: 10, catID: 1, image: require('../android/app/src/main/res/drawable/background.jpg')},
  {Id: 11, catID: 2, image: require('../android/app/src/main/res/drawable/image10.jpg')},
  {Id: 12, catID: 2, image: require('../android/app/src/main/res/drawable/image11.jpg')},
  {Id: 13, catID: 2, image: require('../android/app/src/main/res/drawable/image12.jpg')},
  {Id: 14, catID: 2, image: require('../android/app/src/main/res/drawable/image13.jpg')},
  {Id: 15, catID: 2, image: require('../android/app/src/main/res/drawable/image14.jpg')},
  {Id: 16, catID: 2, image: require('../android/app/src/main/res/drawable/image15.jpg')},
  {Id: 17, catID: 2, image: require('../android/app/src/main/res/drawable/image16.jpg')},
  {Id: 18, catID: 2, image: require('../android/app/src/main/res/drawable/image17.jpg')},
  {Id: 19, catID: 2, image: require('../android/app/src/main/res/drawable/image18.jpg')},
  {Id: 20, catID: 2, image: require('../android/app/src/main/res/drawable/image19.jpg')},
  {Id: 21, catID: 2, image: require('../android/app/src/main/res/drawable/image20.jpg')},
  {Id: 22, catID: 8, image: require('../android/app/src/main/res/drawable/image21.jpg')},
  {Id: 23, catID: 2, image: require('../android/app/src/main/res/drawable/image22.jpg')},
  {Id: 24, catID: 10, image: require('../android/app/src/main/res/drawable/image23.jpg')},
  {Id: 25, catID: 2, image: require('../android/app/src/main/res/drawable/image24.jpg')},
  {Id: 26, catID: 5, image: require('../android/app/src/main/res/drawable/image25.jpg')},
  {Id: 27, catID: 2, image: require('../android/app/src/main/res/drawable/image26.jpg')},
  {Id: 28, catID: 2, image: require('../android/app/src/main/res/drawable/image27.jpg')},
  {Id: 29, catID: 2, image: require('../android/app/src/main/res/drawable/image28.jpg')},
  {Id: 30, catID: 2, image: require('../android/app/src/main/res/drawable/image29.jpg')},
  {Id: 31, catID: 9, image: require('../android/app/src/main/res/drawable/image30.jpeg')},
  {Id: 32, catID: 9, image: require('../android/app/src/main/res/drawable/image31.jpeg')},
  {Id: 33, catID: 9, image: require('../android/app/src/main/res/drawable/image32.jpg')},
  {Id: 34, catID: 9, image: require('../android/app/src/main/res/drawable/image33.jpg')},
  {Id: 35, catID: 9, image: require('../android/app/src/main/res/drawable/image34.jpg')},
  {Id: 36, catID: 9, image: require('../android/app/src/main/res/drawable/image35.jpg')},
  {Id: 37, catID: 9, image: require('../android/app/src/main/res/drawable/image36.jpg')},
  {Id: 38, catID: 9, image: require('../android/app/src/main/res/drawable/image37.jpg')},
];

export const imageResources = [
  {Id: 1, Image: 'image1'},
  {Id: 2, Image: 'image2'},
  {Id: 3, Image: 'image3'},
  {Id: 4, Image: 'image4'},
  {Id: 5, Image: 'image5'},
  {Id: 6, Image: 'image6'},
  {Id: 7, Image: 'image7'},
  {Id: 8, Image: 'image8'},
  {Id: 9, Image: 'image9'},
  {Id: 10, Image: 'background'},
  {Id: 11, Image: 'image10'},
  {Id: 12, Image: 'image11'},
  {Id: 13, Image: 'image12'},
  {Id: 14, Image: 'image13'},
  {Id: 15, Image: 'image14'},
  {Id: 16, Image: 'image15'},
  {Id: 17, Image: 'image16'},
  {Id: 18, Image: 'image17'},
  {Id: 19, Image: 'image18'},
  {Id: 20, Image: 'image19'},
  {Id: 21, Image: 'image20'},
  {Id: 22, Image: 'image21'},
  {Id: 23, Image: 'image22'},
  {Id: 24, Image: 'image23'},
  {Id: 25, Image: 'image24'},
  {Id: 26, Image: 'image25'},
  {Id: 27, Image: 'image26'},
  {Id: 28, Image: 'image27'},
  {Id: 29, Image: 'image28'},
  {Id: 30, Image: 'image29'},
  {Id: 31, Image: 'image30'},
  {Id: 32, Image: 'image31'},
  {Id: 33, Image: 'image32'},
  {Id: 34, Image: 'image33'},
  {Id: 35, Image: 'image34'},
  {Id: 36, Image: 'image35'},
  {Id: 37, Image: 'image36'},
  {Id: 38, Image: 'image37'},
];
